.PHONY: all clean slides-0 slides-1 diagrams

slides-0:
	pandoc -s \
		-t beamer \
		-o rendered/slides_spr23_00_docker.pdf \
		slides_spr23_00_docker.md

slides-1:
	pandoc -s \
		-t beamer \
		-o rendered/slides_spr23_01_handy_sim.pdf \
		slides_spr23_01_handy_sim.md