.PHONY: all clean slides-0 slides-1 slides-2

slides-0:
	pandoc -s \
		-t beamer \
		-o rendered/slides_spr23_00_docker.pdf \
		slides_spr23_00_docker.md

slides-1:
	pandoc -s \
		-t beamer \
		-o rendered/slides_spr23_01_handy_sim.pdf \
		slides_spr23_01_handy_sim.md

slides-2:
	pandoc -s \
		-t beamer \
		-o rendered/slides_spr23_02_pick_and_place.pdf \
		slides_spr23_02_pick_and_place.md